# Base image
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the application for production
RUN npm run build

# Set the environment variable for the production build
ENV NODE_ENV=production

# Expose the port used by the application
EXPOSE 3000

# Start the application
CMD ["npm", "start"]